spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mariadb://localhost:3306/stash
    username: cardstalker
    password: cardstalker

app:
  username: gor1lla
  password: gor1lla
  role: USER